before_script:
    - git clone https://github.com/sstephenson/bats.git /tmp/bats
    - mkdir -p /tmp/local
    - bash /tmp/bats/install.sh /tmp/local
    - export PATH=$PATH:/tmp/local/bin

build:
    stage: build
    script:
        - make

suite1:
    stage: test
    script:
        - make
        - bats test.bats
